name: user_repository_demo
description: Dart package which demonstrates how to interact with user_repository
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  hive: ^2.0.0
  user_repository:
    path: ./user_repository/
