name: odoo_repository
description:  Dart package helps to implement data communication between Odoo and dart client with persistance and offline mode
version: 0.5.1
homepage: https://github.com/ERP-Ukraine/odoo-repository-dart
repository: https://github.com/ERP-Ukraine/odoo-repository-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  odoo_rpc: ^0.4.3
  logger: ^1.0.0
  crypto: ^3.0.0
  pedantic: ^1.11.1
  mutex: ^3.0.0

dev_dependencies:
  test: ^1.16.5
  http: ^0.13.0
