name: odoo_repository
description:  Dart package helps to implement data communication between Odoo and dart client with persistence and offline mode
version: 0.6.0
homepage: https://github.com/ERP-Ukraine/odoo-repository-dart
repository: https://github.com/ERP-Ukraine/odoo-repository-dart

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  equatable: ^2.0.3
  odoo_rpc: ^0.7.1
  logger: ^2.0.0
  crypto: ^3.0.0

  mutex: ^3.0.0

dev_dependencies:
  lints: '>=3.0.0'
  test: ^1.16.5
  http: ^1.1.0
