name: user_repository
description: Dart package which manages the user domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  odoo_rpc: ^0.4.3
  logger: ^1.0.0
  odoo_repository:
    path: ../../.
